In [1]:
import tensorflow as tf
import numpy as np
import cv2
import matplotlib.pyplot as plt
import os
from tensorflow.keras import datasets, layers, models

In [2]:
X = []
Y = []
for i in range(480):
    input = "/home/ltruong/Desktop/hellboy/beet/results/"+"img_"+str(i)+"/real.jpg"
    out_beet = "/home/ltruong/Desktop/hellboy/beet/results/"+"img_"+str(i)+"/beet.jpg"
    out_thistle = "/home/ltruong/Desktop/hellboy/beet/results/"+"img_"+str(i)+"/thistle.jpg"
    img_in = cv2.imread(input)
    img_in = cv2.cvtColor(img_in, cv2.COLOR_RGB2GRAY)
    img_in = cv2.resize(img_in,(64,64))
    img_beet = cv2.imread(out_beet)
    img_beet = cv2.cvtColor(img_beet, cv2.COLOR_RGB2GRAY)
    img_beet = cv2.resize(img_beet,(64,64))
#     img_thistle = cv2.imread(out_thistle)
#     img_thistle = cv2.cvtColor(img_thistle, cv2.COLOR_RGB2GRAY)
    X.append(img_in)
    Y.append(img_beet)
#     Y.append(img_thistle)
X = (np.asarray(X)/255)
Y = (np.asarray(Y)/255)

print(X.shape)
print(Y.shape)

#     cv2.imwrite("levan.jpg",img_in)
#     cv2.imshow("adas",img_in)
#     key = cv2.waitKey()
#     if key == ord('q') or key == 27:
#         cv2.destroyAllWindows()
       
    

(480, 64, 64)
(480, 64, 64)


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
# print(X_train)

In [22]:


model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(64, 64)),
#     tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64,1)),
#     tf.keras.layers.MaxPooling2D((2, 2)),
#     tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
#     tf.keras.layers.MaxPooling2D((2, 2)),
#     tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
#     tf.keras.layers.MaxPooling2D((2, 2)),
#     tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
#     tf.keras.layers.MaxPooling2D((2, 2)),
#     tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
#     tf.keras.layers.MaxPooling2D((2, 2)),
#     tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4096, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(4096, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(4096, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(4096, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    
    tf.keras.layers.Dense(4096, activation=tf.nn.softmax),
    tf.keras.layers.Reshape((64,64))
])
model.summary()
optimizer = tf.keras.optimizers.Adam(lr=0.1)
model.compile(optimizer=optimizer,
              loss='mae',
              metrics=['accuracy'])



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_4 (Flatten)          (None, 4096)              0         
_________________________________________________________________
dense_19 (Dense)             (None, 4096)              16781312  
_________________________________________________________________
dropout_15 (Dropout)         (None, 4096)              0         
_________________________________________________________________
dense_20 (Dense)             (None, 4096)              16781312  
_________________________________________________________________
dropout_16 (Dropout)         (None, 4096)              0         
_________________________________________________________________
dense_21 (Dense)             (None, 4096)              16781312  
_________________________________________________________________
dropout_17 (Dropout)         (None, 4096)              0         
__________

In [23]:
model.fit(X_train, y_train, epochs=10,validation_data=(X_test, y_test),verbose=1)


Train on 384 samples, validate on 96 samples
Epoch 1/10
384/384 [==============================] - 11s 28ms/sample - loss: 0.0521 - acc: 0.1584 - val_loss: 0.0603 - val_acc: 0.2461
Epoch 2/10
384/384 [==============================] - 10s 27ms/sample - loss: 0.0521 - acc: 0.2974 - val_loss: 0.0603 - val_acc: 0.2461
Epoch 3/10
384/384 [==============================] - 11s 27ms/sample - loss: 0.0521 - acc: 0.2974 - val_loss: 0.0603 - val_acc: 0.2461
Epoch 4/10
 96/384 [======>.......................] - ETA: 7s - loss: 0.0508 - acc: 0.2954

KeyboardInterrupt: 

In [20]:
test = cv2.imread("/home/ltruong/Desktop/hellboy/beet/data_beet/im_"+str(18)+".jpg")
test = cv2.cvtColor(test, cv2.COLOR_RGB2GRAY)
test = cv2.resize(test,(64,64))
test = (np.asarray(test)/255).reshape(1,64,64)

# print (test)
out_test = model.predict(test)
print(out_test)
cv2.imwrite("levan.jpg",out_test[0])
cv2.imshow("adas",out_test[0])
key = cv2.waitKey()
if key == ord('q') or key == 27:
    cv2.destroyAllWindows()

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
