In [1]:
import tensorflow as tf
import numpy as np
import cv2
import matplotlib.pyplot as plt
import os
from tensorflow.keras import datasets, layers, models

In [18]:
X = []
Y = []
for i in range(480):
    input = "results/"+"img_"+str(i)+"/exg.jpg"
    out_beet = "results/"+"img_"+str(i)+"/beet.jpg"
    out_thistle = "results/"+"img_"+str(i)+"/thistle.jpg"
    img_in = cv2.imread(input)
    img_in = cv2.cvtColor(img_in, cv2.COLOR_RGB2GRAY)
    img_in = cv2.resize(img_in,(64,64))
    img_beet = cv2.imread(out_beet)
    img_beet = cv2.cvtColor(img_beet, cv2.COLOR_RGB2GRAY)
    img_beet = cv2.resize(img_beet,(64,64))
#     img_thistle = cv2.imread(out_thistle)
#     img_thistle = cv2.cvtColor(img_thistle, cv2.COLOR_RGB2GRAY)
    X.append(img_in)
    Y.append(img_beet)
#     Y.append(img_thistle)
X = (np.asarray(X)/255)
Y = (np.asarray(Y)/255)

print(X.shape)
print(Y.shape)

#     cv2.imwrite("levan.jpg",img_in)
#     cv2.imshow("adas",img_in)
#     key = cv2.waitKey()
#     if key == ord('q') or key == 27:
#         cv2.destroyAllWindows()
       
    

(480, 64, 64)
(480, 64, 64)


In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)
# print(X_train)

In [23]:


model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(64, 64)),
#     tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64,1)),
#     tf.keras.layers.MaxPooling2D((2, 2)),
#     tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
#     tf.keras.layers.MaxPooling2D((2, 2)),
#     tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
#     tf.keras.layers.MaxPooling2D((2, 2)),
#     tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
#     tf.keras.layers.MaxPooling2D((2, 2)),
#     tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
#     tf.keras.layers.MaxPooling2D((2, 2)),
#     tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4096, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(4096, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(4096, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(4096, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.1),
    tf.keras.layers.Dense(4096, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.1),
 
    tf.keras.layers.Dense(4096, activation=tf.nn.softmax),
    tf.keras.layers.Reshape((64,64))
])
model.summary()
optimizer = tf.keras.optimizers.Adam(lr=0.1)
model.compile(optimizer=optimizer,
              loss='mse',
              metrics=['accuracy'])



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_8 (Flatten)          (None, 4096)              0         
_________________________________________________________________
dense_21 (Dense)             (None, 4096)              16781312  
_________________________________________________________________
dropout_13 (Dropout)         (None, 4096)              0         
_________________________________________________________________
dense_22 (Dense)             (None, 4096)              16781312  
_________________________________________________________________
dropout_14 (Dropout)         (None, 4096)              0         
_________________________________________________________________
dense_23 (Dense)             (None, 4096)              16781312  
_________________________________________________________________
dropout_15 (Dropout)         (None, 4096)              0         
__________

In [24]:
model.fit(X_train, y_train, epochs=10,validation_data=(X_test, y_test),verbose=1)


Train on 384 samples, validate on 96 samples
Epoch 1/10
384/384 [==============================] - 50s 129ms/step - loss: 0.0474 - acc: 0.0133 - val_loss: 0.0475 - val_acc: 0.0146
Epoch 2/10
384/384 [==============================] - 30s 78ms/step - loss: 0.0475 - acc: 0.0635 - val_loss: 0.0477 - val_acc: 0.2524
Epoch 3/10
384/384 [==============================] - 30s 79ms/step - loss: 0.0477 - acc: 0.2956 - val_loss: 0.0477 - val_acc: 0.2524
Epoch 4/10
384/384 [==============================] - 30s 77ms/step - loss: 0.0477 - acc: 0.2956 - val_loss: 0.0477 - val_acc: 0.2524
Epoch 5/10
384/384 [==============================] - 30s 77ms/step - loss: 0.0477 - acc: 0.2956 - val_loss: 0.0477 - val_acc: 0.2524
Epoch 6/10
384/384 [==============================] - 29s 76ms/step - loss: 0.0477 - acc: 0.2956 - val_loss: 0.0477 - val_acc: 0.2524
Epoch 7/10
384/384 [==============================] - 29s 75ms/step - loss: 0.0477 - acc: 0.2956 - val_loss: 0.0477 - val_acc: 0.2524
Epoch 8/10
384/3

In [26]:
test = cv2.imread("data_beet/im_"+str(1)+".jpg")
test = cv2.cvtColor(test, cv2.COLOR_RGB2GRAY)
test = cv2.resize(test,(64,64))
test = (np.asarray(test)/255).reshape(1,64,64)

# print (test)
out_test = model.predict(test).reshape(64,64)
print(out_test)
cv2.imwrite("levan.jpg",out_test)
cv2.imshow("adas",out_test)
key = cv2.waitKey()
if key == ord('q') or key == 27:
    cv2.destroyAllWindows()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
